{"uuid": "504c91d6-c8f7-42c6-88d9-cc59c925f575", "children": ["afa26ccd-67b7-49f5-b1b7-5157d37972c9", "ebd4232d-dd6a-40da-8252-eb1a31f65ed6", "54033597-8b02-4e55-8a3b-713a3ef08636", "3844973b-001c-4bb5-9a72-4e540f49d316", "010a297a-2a67-485b-95cb-b1347095d7f1", "2c0b26bb-46ec-44aa-b7d6-20e5ddaf01ef", "082345cf-1b7a-4dd6-9eb4-9737fffffff3", "93686c7a-71ff-47d3-996e-2e5eb78768e1", "1b7379d2-1a73-4e42-bcad-493148943c98", "3b3704c7-0a2b-4736-9f95-a787bb2e2c3f"], "befores": [{"name": "initWebDriver", "status": "broken", "statusDetails": {"message": "Exception: Wrong input, unrecognized browser!\n", "trace": "  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\AtidAutomation\\FinalProjectInfrastructure\\WebMobile\\TestCases\\conftest.py\", line 68, in initWebDriver\n    edriver = GetWebDriver()\n  File \"D:\\AtidAutomation\\FinalProjectInfrastructure\\WebMobile\\TestCases\\conftest.py\", line 100, in GetWebDriver\n    raise Exception(\"Wrong input, unrecognized browser!\")\n"}, "start": 1665992866176, "stop": 1665992866178}], "start": 1665992866176, "stop": 1665992866527}